
services:

  nginx:
    image: kauech/nginx:openssl
    container_name: dockeasy-nginx
    restart: unless-stopped

    ports:
      - "${DOCKEASY_NGINX_HTTP_PORT:-80}:80"
      - "${DOCKEASY_NGINX_HTTPS_PORT:-443}:443"

      - "${DOCKEASY_ELECTRUM_SERVER_PORT:-50001}:50001"
      - "${DOCKEASY_ELECTRUM_SERVER_TLS_PORT:-50002}:50002"

    environment:
      NGINX_DOMAINS: "*.${DOCKEASY_DOMAIN:-local} ${DOCKEASY_DOMAIN:-local} localhost *.localhost *.onion *.${DOCKEASY_PKDNS_PUBKEY:-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} ${DOCKEASY_PKDNS_PUBKEY:-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}"
      
      NGINX_FORCE_HTTPS: ${DOCKEASY_NGINX_FORCE_HTTPS:-true}

      NGINX_STREAM_SERVER_ELECTRS: |
        listen 50001;
        proxy_pass electrs:50001;

      NGINX_STREAM_SERVER_ELECTRS_TLS: |
        listen 50002;
        proxy_pass electrs:50001;

      NGINX_HTTP: |
        client_max_body_size 0;

      NGINX_MAP_HOST_AS_SERVICE_SUBDOMAIN: |
        ~^(?<subdomain>.+)\.${DOCKEASY_DOMAIN:-local}$                                    $$subdomain;
        ~^(?<subdomain>.+)\.${DOCKEASY_PKDNS_PUBKEY:-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}$   $$subdomain;
        ~^(?<subdomain>.+)\.localhost$                                                    $$subdomain;
        ~^(?<subdomain>[^.]+)\..+\.onion$                                                 $$subdomain;

        default                                                                           "";

      NGINX_MAP_SERVICE_SUBDOMAIN_AS_TARGET: |
        bookstack         http://bookstack:80;
        blinko            http://blinko-website:1111;
        docmost           http://docmost:3000;
 
        s3                http://minio:9000;
        minio             http://minio-console:9090;
        affine            http://affine:3010;

        garage            http://garage-web:3909;

        gpt               http://open-webui:8080;

        open-webui        http://open-webui:8080;

        trilium           http://trilium:8080;

        outline           http://outline:3000;

        memos             http://memos:5230;

        gitea             http://gitea:3000;

        git               http://gitea:3000;

        nextcloud         http://nextcloud:80;

        collabora         http://nextcloud-collabora:9980;

        seafile           http://seafile:80;

        nginx             http://nginx-proxy-manager:81;

        ghost             http://ghost:2368;

        adguard           http://adguard:80;

        adguard-setup     http://adguard:3000;

        docker            http://registry:5000;
        docker-hub        http://registry-browser:8080;

        rustfs            http://rustfs:9000;

        metube            http://metube:8081;

        writefreely       http://writefreely:8080;

        code              http://code-server:8443;

        obsidian-couchdb  http://obsidian-couchdb:5984;

        perlite           http://perlite-web:80;

        silverbullet      http://silverbullet:3000;

        default           ${DOCKEASY_NGINX_DEFAULT_TARGET:-http://nginx-proxy-manager:80};
    
    volumes:
      - "./data/letsencrypt:/etc/letsencrypt"

    networks:
      - dockeasy

networks:
  dockeasy:
    external: true